Readiness probe for sentinel and exporter
DandyDeveloper/charts pull request #114
Opened 2021-02-19 20:38 UTC by michael-michalski

Signed-off-by: Michael Michalski <michaelmartinmichalski@gmail.com>

#### What this PR does / why we need it:
The chart currently lacks readiness probes for sentinels and exporter pods

#### Which issue this PR fixes

#### Special notes for your reviewer:
Follow up after following pr:
https://github.com/DandyDeveloper/charts/pull/109

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2021-02-20 06:57 UTC, DandyDeveloper requested changes
Minor update needed.

2021-02-20 06:57 UTC, DandyDeveloper commented on charts/redis-ha/values.yaml
> +  readiness:
`readinessProbe`?

2021-02-21 17:48 UTC, michael-michalski commented on charts/redis-ha/values.yaml
> +  readiness:
Thanks for pointing out, ups.

2021-02-23 10:45 UTC, michael-michalski commented
@DandyDeveloper Are we happy :D

2021-02-25 08:17 UTC, DandyDeveloper approved these changes

2021-02-25 08:17 UTC, merged