Network policies
DandyDeveloper/charts pull request #126
Opened 2021-04-26 07:29 UTC by haljin

#### What this PR does / why we need it:

#### Which issue this PR fixes
Closes #106 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2021-05-10 01:17 UTC, DandyDeveloper requested changes

2021-05-10 07:41 UTC, haljin commented on charts/redis-ha/templates/redis-ha-network-policy.yaml
> +  name: {{ template "redis-ha.fullname" . }}-pdb
Oops, completely missed that

2021-08-04 12:19 UTC, jdheyburn commented
Hey, this looks like a useful PR. Is it possible for it to be merged in after a rebase?

2021-08-04 12:21 UTC, jdheyburn commented on charts/redis-ha/README.md
> +| `networkPolicy.kubeDNSLabels` | Pod labels for Kube DNS | `[]` |
This should be updated to reflect the new values: `clientSelector` and `dnsSelector`.

2021-08-04 12:21 UTC, jdheyburn commented on charts/redis-ha/templates/redis-ha-network-policy.yaml
> +{{- end }}
New line required here

2021-08-05 00:07 UTC, DandyDeveloper commented
@haljin @jdheyburn Yes, I agree. I think the structure here is too rigid. 

I like the linked template. We should use that. 

If you have the time, can you create another PR @jdheyburn? I think this one may have gone stale.

2021-08-05 00:12 UTC, DandyDeveloper commented
This also closes: https://github.com/DandyDeveloper/charts/issues/83

2021-08-19 12:02 UTC, sean-mcgimpsey commented
Any update here ? We're really keen to implement network policies to isolate our redis statefulsets

2021-08-19 15:43 UTC, jdheyburn commented
I've raised #146 which aims to introduce a minimal, but flexible Network Policy for Redis Pods. Please take a look and continue the discussion there.

@sean-mcgimpsey @DandyDeveloper

2021-08-20 06:32 UTC, haljin commented
I guess I will abandon this then, thanks @jdheyburn !

2021-08-20 06:32 UTC, closed without merging