[redis-ha]Terminate TLS on HAproxy
DandyDeveloper/charts pull request #148
Opened 2021-08-20 12:50 UTC by GGre4

#### What this PR does / why we need it:

To terminate TLS on HAProxy instead of terminating TLS on redis.

#### Which issue this PR fixes
Currently the chart does not support terminating TLS on haproxy, additionally the chart does not support using redis with both TLS enabled and TLS disabled. To achieve this modifying the haproxy service is needed to have more control on ports.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ X] Chart Version bumped
- [ X] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2021-08-30 01:27 UTC, DandyDeveloper requested changes
@GGre4 Looks good, will test. Have a number of PRs to work through, can you just fix the spelling error?

2021-08-30 01:27 UTC, DandyDeveloper commented on charts/redis-ha/README.md
> +| `haproxy.image.rserviceAccountName`| HAProxy serviceAccountName
`rserviceAccountName` Typo?

2021-09-03 13:21 UTC, GGre4 commented
Typo has been updated

2021-12-29 14:42 UTC, GGre4 commented
@DandyDeveloper  Any reason why this PR was not approved ? i had updated it to reflect with the updated chart version and such but it was not reviewed

2021-12-29 16:18 UTC, closed without merging

2022-01-04 07:46 UTC, DandyDeveloper commented
@GGre4 Can you reopen? I'm really not sure, it just flew under my radar. I'm sorry.