[stable/redis-ha] Support topologySpreadConstraints
DandyDeveloper/charts pull request #184
Opened 2022-02-04 02:57 UTC by TheRealDwright

Closes #128

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #128

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2022-03-01 23:35 UTC, DandyDeveloper commented
@TheRealDwright Sorry, I've neglected this PR, the autoassign isn't working. I'll take a look and test these constraints when I have a free moment.

2022-03-01 23:37 UTC, TheRealDwright commented
> @TheRealDwright Sorry, I've neglected this PR, the autoassign isn't working. I'll take a look and test these constraints when I have a free moment.

No problem, we've already tested this rigorously in our production environment, but feel free to do your due diligence and let me know if you want me to update it with any changes.

2022-03-29 23:40 UTC, TheRealDwright commented
Hey @DandyDeveloper - is there anything you would like me to do/change on this?

2022-05-25 01:03 UTC, DandyDeveloper requested changes

2022-05-25 01:03 UTC, DandyDeveloper commented on charts/redis-ha/values.yaml
> +
Can we have all the options visible in the values? 

```suggestion
topologySpreadConstraints:
  enabled: false
  maxSkew: ""
  topologyKey: ""
  whenUnsatisfiable: "" 
```

With this, think we're good to merge in.

2022-05-25 01:11 UTC, DandyDeveloper approved these changes

2022-05-25 01:21 UTC, merged

2022-05-25 09:50 UTC, mkilchhofer commented
Hmm maybe we should combine this with `.Values.hardAntiAffinity`?

I think it would make sense to disable the affinity completely when using topologySpreadConstraints. WDYT @TheRealDwright and @DandyDeveloper ?

2022-05-26 00:30 UTC, DandyDeveloper commented
@mkilchhofer Technically, both can be used in conjunction to still define hard scheduling requirements for pods. Best "overview" of this I can find would be this: https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/#usage-along-with-nodeselector-nodeaffinity

I don't think the two should be connected.

2022-05-26 03:27 UTC, TheRealDwright commented
Agree with @DandyDeveloper - all this PR is intended to facilitate is the even distribution of pods between cluster zones (e.g. AWS Availability Zones) for high availability purposes. It's only loosely related to anti-affinity.